{
 "title": "RMD Server",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(rmd_accounts,job)" } }
  ]
 },
 "panels": [
  { "title": "Accounts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of accounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmd_accounts{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmd_active_sessions{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of accounts with recently failed logins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmd_failed_login_accounts{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stored Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Number of locations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmd_locations{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of pictures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmd_pictures{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of pending commands",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmd_pending_commands{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average number of locations per account",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmd_locations{job=\"$job\"}/rmd_accounts{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average number of pictures per account",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmd_pictures{job=\"$job\"}/rmd_accounts{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}